# Generated by Django 5.2.5 on 2026-05-21 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('media_assets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tip', 'Tip'), ('suspicious_movement', 'Suspicious Movement'), ('abnormal_sighting', 'Abnormal Sighting'), ('road_threat', 'Road Threat'), ('camp_indicator', 'Camp Indicator'), ('fire_smoke', 'Fire / Smoke'), ('flood', 'Flood'), ('violence', 'Violence'), ('kidnapping', 'Kidnapping'), ('armed_robbery', 'Armed Robbery'), ('other', 'Other')], default='tip', max_length=32)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('triaged', 'Triaged'), ('clustered', 'Clustered'), ('escalated', 'Escalated'), ('dismissed', 'Dismissed')], default='raw', max_length=16)),
                ('confidence', models.CharField(choices=[('raw', 'Raw'), ('low', 'Low Confidence'), ('emerging', 'Emerging'), ('corroborated', 'Corroborated'), ('high', 'High Confidence'), ('disputed', 'Disputed')], default='raw', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordinate_precision_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('route_hint', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_entities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='incidents.signalcluster')),
                ('source_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='users.sourceprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('note', 'Note')], default='note', max_length=16)),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_evidence', to='media_assets.mediaasset')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='signals.signal')),
            ],
            options={
                'ordering': ['signal', '-created_at'],
            },
        ),
    ]
