# Generated by Django 5.2.5 on 2026-05-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('geofences', '0001_initial'),
        ('incidents', '0001_initial'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='incidents.signalcluster'),
        ),
        migrations.AddField(
            model_name='alert',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='geofences.geofence'),
        ),
        migrations.AddField(
            model_name='alert',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='alert',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='incidents.pattern'),
        ),
        migrations.AddField(
            model_name='alert',
            name='watch_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='risk.watchzone'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule'),
        ),
    ]
