from __future__ import annotations

from datetime import timedelta
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone

from apps.alerts.models import Alert, AlertRule
from apps.geofences.models import Geofence, GeofenceType
from apps.incidents.models import (
    Incident,
    IncidentStatus,
    IncidentType,
    Pattern,
    PatternStatus,
    SignalCluster,
)
from apps.risk.models import RiskLevel, RiskSnapshot, WatchZone, WatchZoneStatus
from apps.signals.models import ConfidenceLevel, SeverityLevel, Signal, SignalCategory, SignalStatus
from apps.users.models import ReliabilityBand, SourceProfile, SourceType, UserProfile, UserRole


DEMO_FLAG = {"demo_seed": True}
DEMO_USERNAME = "demo_analyst"
DEMO_PASSWORD = "GeoPulse123!"


def dec(value: str) -> Decimal:
    return Decimal(value)


class Command(BaseCommand):
    help = "Seed AegisMap with realistic demo intelligence data for the dashboard."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing demo-seeded records before recreating them.",
        )

    def handle(self, *args, **options):
        if options["reset"]:
            self._clear_demo_data()

        now = timezone.now()
        user = self._ensure_demo_user()
        sources = self._ensure_sources(user, now)
        rules = self._ensure_alert_rules()
        geofences = self._ensure_geofences()
        watch_zones = self._ensure_watch_zones(now)
        clusters = self._ensure_clusters(now)
        patterns = self._ensure_patterns(clusters, now)
        signals = self._ensure_signals(user, sources, clusters, now)
        incidents = self._ensure_incidents(patterns, signals, now)
        self._ensure_risk_snapshots(watch_zones, patterns, incidents, now)
        alerts = self._ensure_alerts(rules, watch_zones, geofences, clusters, patterns, incidents, now)

        self.stdout.write(
            self.style.SUCCESS(
                "Demo intelligence ready: "
                f"{len(signals)} signals, {len(incidents)} incidents, {len(watch_zones)} watch zones, {len(alerts)} alerts."
            )
        )
        self.stdout.write(
            self.style.WARNING(
                f"Login with username '{DEMO_USERNAME}' and password '{DEMO_PASSWORD}'."
            )
        )

    def _clear_demo_data(self):
        Alert.objects.filter(metadata__demo_seed=True).delete()
        RiskSnapshot.objects.filter(
            watch_zone__metadata__demo_seed=True
        ).delete()
        Incident.objects.filter(metadata__demo_seed=True).delete()
        Signal.objects.filter(metadata__demo_seed=True).delete()
        Pattern.objects.filter(metadata__demo_seed=True).delete()
        SignalCluster.objects.filter(metadata__demo_seed=True).delete()
        WatchZone.objects.filter(metadata__demo_seed=True).delete()
        Geofence.objects.filter(metadata__demo_seed=True).delete()
        SourceProfile.objects.filter(metadata__demo_seed=True).delete()
        get_user_model().objects.filter(username=DEMO_USERNAME).delete()

    def _ensure_demo_user(self):
        User = get_user_model()
        user, _ = User.objects.get_or_create(
            username=DEMO_USERNAME,
            defaults={
                "email": "demo.analyst@geopulse.local",
                "first_name": "GeoPulse",
                "last_name": "Analyst",
            },
        )
        user.set_password(DEMO_PASSWORD)
        user.is_staff = True
        user.save(update_fields=["password", "is_staff"])

        UserProfile.objects.update_or_create(
            user=user,
            defaults={
                "display_name": "GeoPulse Demo Analyst",
                "role": UserRole.ANALYST,
                "organization": "GeoPulse AI Demo Cell",
                "region_name": "Lagos - Abuja - Kaduna Corridor",
                "is_active_operator": True,
                "metadata": DEMO_FLAG,
            },
        )
        return user

    def _ensure_sources(self, user, now):
        source_specs = [
            {
                "label": "Rapid Response Hotline",
                "source_type": SourceType.USER,
                "reliability_band": ReliabilityBand.HIGH,
                "trust_score": Decimal("0.84"),
                "report_count": 18,
                "verified_signal_count": 12,
            },
            {
                "label": "Northwest Civic Monitor",
                "source_type": SourceType.CIVIC_MONITOR,
                "reliability_band": ReliabilityBand.TRUSTED,
                "trust_score": Decimal("0.91"),
                "report_count": 41,
                "verified_signal_count": 33,
            },
            {
                "label": "Transport Union Watch",
                "source_type": SourceType.TRANSPORT,
                "reliability_band": ReliabilityBand.MODERATE,
                "trust_score": Decimal("0.72"),
                "report_count": 27,
                "verified_signal_count": 15,
            },
            {
                "label": "Drone Patrol Delta-4",
                "source_type": SourceType.DRONE,
                "reliability_band": ReliabilityBand.TRUSTED,
                "trust_score": Decimal("0.95"),
                "report_count": 63,
                "verified_signal_count": 56,
            },
        ]

        sources = {}
        for spec in source_specs:
            source, _ = SourceProfile.objects.update_or_create(
                label=spec["label"],
                defaults={
                    "user": user,
                    "source_type": spec["source_type"],
                    "reliability_band": spec["reliability_band"],
                    "trust_score": spec["trust_score"],
                    "report_count": spec["report_count"],
                    "verified_signal_count": spec["verified_signal_count"],
                    "disputed_signal_count": 1,
                    "last_seen_at": now - timedelta(minutes=18),
                    "notes": "Demo seed source profile.",
                    "metadata": DEMO_FLAG,
                },
            )
            sources[spec["label"]] = source
        return sources

    def _ensure_alert_rules(self):
        defaults = [
            {
                "name": "High severity corroborated incident",
                "description": "Trigger when a high severity corroborated incident is detected.",
                "min_confidence": ConfidenceLevel.CORROBORATED,
                "min_severity": SeverityLevel.HIGH,
                "threshold_count": 1,
                "radius_meters": 2500,
                "window_minutes": 90,
            },
            {
                "name": "Escalating corridor activity",
                "description": "Trigger when repeated corridor signals escalate over a short window.",
                "min_confidence": ConfidenceLevel.EMERGING,
                "min_severity": SeverityLevel.MEDIUM,
                "threshold_count": 3,
                "radius_meters": 5000,
                "window_minutes": 180,
            },
        ]
        rules = {}
        for payload in defaults:
            rule, _ = AlertRule.objects.get_or_create(name=payload["name"], defaults=payload)
            rules[payload["name"]] = rule
        return rules

    def _ensure_geofences(self):
        specs = [
            {
                "name": "Lekki-Epe Expressway Corridor",
                "geofence_type": GeofenceType.HIGHWAY,
                "lat": dec("6.469800"),
                "lng": dec("3.585200"),
                "radius": 4200,
                "description": "High traffic route monitored for rapid incident escalation.",
            },
            {
                "name": "Abuja City Gate Perimeter",
                "geofence_type": GeofenceType.FACILITY,
                "lat": dec("8.946200"),
                "lng": dec("7.398600"),
                "radius": 2800,
                "description": "Strategic access control area.",
            },
        ]
        geofences = {}
        for spec in specs:
            geofence, _ = Geofence.objects.update_or_create(
                name=spec["name"],
                defaults={
                    "geofence_type": spec["geofence_type"],
                    "centroid_latitude": spec["lat"],
                    "centroid_longitude": spec["lng"],
                    "radius_meters": spec["radius"],
                    "description": spec["description"],
                    "notify_on_signal": True,
                    "notify_on_incident": True,
                    "metadata": DEMO_FLAG,
                },
            )
            geofences[spec["name"]] = geofence
        return geofences

    def _ensure_watch_zones(self, now):
        specs = [
            {
                "name": "Lekki Peninsula",
                "zone_type": "urban_corridor",
                "risk": RiskLevel.HIGH,
                "score": Decimal("78.50"),
                "lat": dec("6.447400"),
                "lng": dec("3.535100"),
                "notes": "Repeated armed robbery and suspicious movement signals near commuter routes.",
            },
            {
                "name": "Abuja Southern Approach",
                "zone_type": "route_hub",
                "risk": RiskLevel.MEDIUM,
                "score": Decimal("64.20"),
                "lat": dec("8.913600"),
                "lng": dec("7.454700"),
                "notes": "Elevated approach risk with intermittent anomaly reports.",
            },
            {
                "name": "Kaduna Forest Edge",
                "zone_type": "rural_watch",
                "risk": RiskLevel.CRITICAL,
                "score": Decimal("91.40"),
                "lat": dec("10.492900"),
                "lng": dec("7.398600"),
                "notes": "High confidence threat clustering around forest ingress routes.",
            },
        ]
        zones = {}
        for spec in specs:
            zone, _ = WatchZone.objects.update_or_create(
                name=spec["name"],
                defaults={
                    "zone_type": spec["zone_type"],
                    "status": WatchZoneStatus.ACTIVE,
                    "current_risk_level": spec["risk"],
                    "current_risk_score": spec["score"],
                    "centroid_latitude": spec["lat"],
                    "centroid_longitude": spec["lng"],
                    "notes": spec["notes"],
                    "metadata": DEMO_FLAG,
                    "last_evaluated_at": now - timedelta(minutes=12),
                },
            )
            zones[spec["name"]] = zone
        return zones

    def _ensure_clusters(self, now):
        specs = [
            {
                "name": "Lekki night movement cluster",
                "cluster_type": "movement",
                "confidence": ConfidenceLevel.CORROBORATED,
                "status": PatternStatus.MONITORING,
                "lat": dec("6.452100"),
                "lng": dec("3.558400"),
                "radius": 2200,
                "summary": "Night movement and robbery signals clustering along Lekki axis.",
            },
            {
                "name": "Kaduna forest ingress cluster",
                "cluster_type": "proximity",
                "confidence": ConfidenceLevel.HIGH,
                "status": PatternStatus.ESCALATED,
                "lat": dec("10.501800"),
                "lng": dec("7.412500"),
                "radius": 4800,
                "summary": "Multiple suspicious movement and camp indicators around the forest edge.",
            },
        ]
        clusters = {}
        for spec in specs:
            cluster, _ = SignalCluster.objects.update_or_create(
                name=spec["name"],
                defaults={
                    "cluster_type": spec["cluster_type"],
                    "confidence": spec["confidence"],
                    "status": spec["status"],
                    "centroid_latitude": spec["lat"],
                    "centroid_longitude": spec["lng"],
                    "radius_meters": spec["radius"],
                    "started_at": now - timedelta(hours=spec["radius"] // 1000),
                    "last_seen_at": now - timedelta(minutes=18),
                    "summary": spec["summary"],
                    "metadata": DEMO_FLAG,
                },
            )
            clusters[spec["name"]] = cluster
        return clusters

    def _ensure_patterns(self, clusters, now):
        specs = [
            {
                "name": "Lekki commuter threat escalation",
                "cluster": clusters["Lekki night movement cluster"],
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "status": PatternStatus.MONITORING,
                "hint": "Lekki - Ajah evening route",
                "lat": dec("6.455300"),
                "lng": dec("3.566100"),
                "summary": "Escalating pattern of robbery reports and suspicious bike movement near commuter choke points.",
            },
            {
                "name": "Kaduna staging pattern",
                "cluster": clusters["Kaduna forest ingress cluster"],
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.CRITICAL,
                "status": PatternStatus.ESCALATED,
                "hint": "Birnin Gwari forest ingress",
                "lat": dec("10.499500"),
                "lng": dec("7.405800"),
                "summary": "Repeated sightings, route indicators, and camp evidence suggest organized staging activity.",
            },
        ]
        patterns = {}
        for spec in specs:
            pattern, _ = Pattern.objects.update_or_create(
                name=spec["name"],
                defaults={
                    "cluster": spec["cluster"],
                    "confidence": spec["confidence"],
                    "severity": spec["severity"],
                    "status": spec["status"],
                    "geographic_hint": spec["hint"],
                    "centroid_latitude": spec["lat"],
                    "centroid_longitude": spec["lng"],
                    "first_detected_at": now - timedelta(hours=9),
                    "last_detected_at": now - timedelta(minutes=20),
                    "summary": spec["summary"],
                    "metadata": DEMO_FLAG,
                },
            )
            patterns[spec["name"]] = pattern
        return patterns

    def _demo_incident_specs(self):
        return [
            {
                "signal_title": "Armed robbery report at Admiralty Way slip road",
                "signal_description": "Driver reports coordinated robbery attempt targeting vehicles slowing at the slip road.",
                "incident_title": "Armed robbery cluster near Lekki toll corridor",
                "source": "Rapid Response Hotline",
                "cluster": "Lekki night movement cluster",
                "pattern": "Lekki commuter threat escalation",
                "category": SignalCategory.ARMED_ROBBERY,
                "incident_type": IncidentType.ARMED_ROBBERY,
                "signal_status": SignalStatus.ESCALATED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.CRITICAL,
                "state": "Lagos",
                "location": "Lekki Toll Corridor, Lagos",
                "lat": dec("6.445800"),
                "lng": dec("3.553000"),
                "route": "Victoria Island - Lekki",
                "summary": "Coordinated robbery activity reported across adjacent choke points with corroborating movement indicators.",
                "minutes_ago": 11,
            },
            {
                "signal_title": "Flooded low-visibility segment near Third Mainland feeder",
                "signal_description": "Standing water reducing visibility and forcing traffic bunching at the feeder segment.",
                "incident_title": "Localized flood hazard on Third Mainland feeder",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Third Mainland Feeder, Lagos",
                "lat": dec("6.507400"),
                "lng": dec("3.392700"),
                "route": "Third Mainland - Lagos Island",
                "summary": "Water accumulation and traffic bunching are increasing route vulnerability for commuters.",
                "minutes_ago": 58,
            },
            {
                "signal_title": "Diesel tanker fire near Ojodu Berger interchange",
                "signal_description": "A diesel tanker sparked at the interchange shoulder, producing dense smoke across the merge lane.",
                "incident_title": "Diesel tanker fire near Ojodu Berger interchange",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Ojodu Berger Interchange, Lagos",
                "lat": dec("6.639800"),
                "lng": dec("3.371000"),
                "route": "Lagos-Ibadan Expressway",
                "summary": "A tanker fire is constraining visibility and forcing diversions near a major interchange.",
                "minutes_ago": 34,
            },
            {
                "signal_title": "Multi-vehicle collision on Ikorodu Road inbound",
                "signal_description": "Three vehicles collided on the inbound carriageway, blocking one lane during peak movement.",
                "incident_title": "Multi-vehicle collision on Ikorodu Road inbound",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Ikorodu Road Inbound, Lagos",
                "lat": dec("6.573900"),
                "lng": dec("3.384200"),
                "route": "Ikorodu Road - Maryland",
                "summary": "A fresh collision is slowing inbound traffic and creating a hazardous stop-start segment.",
                "minutes_ago": 46,
            },
            {
                "signal_title": "Flooded carriageway near Lekki conservation axis",
                "signal_description": "Rapid drainage overflow has submerged the curb lane close to the conservation axis.",
                "incident_title": "Flooded carriageway near Lekki conservation axis",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Lekki Conservation Axis, Lagos",
                "lat": dec("6.437300"),
                "lng": dec("3.563000"),
                "route": "Lekki-Epe Expressway",
                "summary": "Floodwater is narrowing passable lanes and increasing spin-out risk along the corridor.",
                "minutes_ago": 83,
            },
            {
                "signal_title": "Unsafe route advisory around Mile 2 bridge approach",
                "signal_description": "Persistent gridlock, shoulder encroachment, and stalled vehicles are forcing risky route behavior.",
                "incident_title": "Unsafe route advisory around Mile 2 bridge approach",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Mile 2 Bridge Approach, Lagos",
                "lat": dec("6.463000"),
                "lng": dec("3.303400"),
                "route": "Badagry Expressway",
                "summary": "The approach remains unstable as heavy vehicles force unpredictable lane changes near the bridge.",
                "minutes_ago": 27,
            },
            {
                "signal_title": "Container obstruction on Apapa-Oshodi expressway",
                "signal_description": "A fallen container has blocked the service lane and pushed trailers into live traffic.",
                "incident_title": "Container obstruction on Apapa-Oshodi expressway",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Apapa-Oshodi Expressway, Lagos",
                "lat": dec("6.457800"),
                "lng": dec("3.338600"),
                "route": "Apapa Port Corridor",
                "summary": "A container spill is constricting throughput and raising collision risk on the expressway.",
                "minutes_ago": 71,
            },
            {
                "signal_title": "Fire outbreak at market strip near Yaba corridor",
                "signal_description": "Traders reported a fast-moving electrical fire spreading across a roadside market strip.",
                "incident_title": "Fire outbreak at market strip near Yaba corridor",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.RESOLVED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Yaba Market Corridor, Lagos",
                "lat": dec("6.514400"),
                "lng": dec("3.376800"),
                "route": "Herbert Macaulay Way",
                "summary": "A contained market fire disrupted movement and utility access before firefighters stabilized the scene.",
                "minutes_ago": 132,
            },
            {
                "signal_title": "Thermal anomaly near Kaduna forest edge",
                "signal_description": "Drone thermal scan picked up repeated heat signatures around a temporary clearing.",
                "incident_title": "Kaduna forest edge staging activity",
                "source": "Drone Patrol Delta-4",
                "cluster": "Kaduna forest ingress cluster",
                "pattern": "Kaduna staging pattern",
                "category": SignalCategory.SUSPICIOUS_ACTIVITY,
                "incident_type": IncidentType.SUSPICIOUS_ACTIVITY,
                "signal_status": SignalStatus.ESCALATED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.CRITICAL,
                "state": "Kaduna",
                "location": "Kaduna Forest Edge",
                "lat": dec("10.499600"),
                "lng": dec("7.408900"),
                "route": "Birnin Gwari Forest Track",
                "summary": "Thermal signatures, movement reports, and route indicators suggest a live staging area near the forest boundary.",
                "minutes_ago": 16,
            },
            {
                "signal_title": "Abnormal sighting on Abuja southbound approach",
                "signal_description": "Unmarked pickup observed stopping repeatedly along the approach corridor.",
                "incident_title": "Abuja southbound anomaly watch",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.SUSPICIOUS_ACTIVITY,
                "incident_type": IncidentType.SUSPICIOUS_ACTIVITY,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "FCT Abuja",
                "location": "Abuja Southern Approach",
                "lat": dec("8.914100"),
                "lng": dec("7.455900"),
                "route": "Airport - City Gate",
                "summary": "Intermittent anomaly reports around the approach corridor remain under analyst review.",
                "minutes_ago": 42,
            },
            {
                "signal_title": "Multi-vehicle collision near Airport Road interchange",
                "signal_description": "A rear-end chain collision is slowing both the service lane and the main carriageway.",
                "incident_title": "Multi-vehicle collision near Airport Road interchange",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "FCT Abuja",
                "location": "Airport Road Interchange, Abuja",
                "lat": dec("8.997200"),
                "lng": dec("7.381000"),
                "route": "Airport Road",
                "summary": "A fresh collision has created dense queuing at a critical inbound interchange.",
                "minutes_ago": 23,
            },
            {
                "signal_title": "Flooded underpass near Area 1 approach",
                "signal_description": "The underpass is collecting runoff quickly and forcing vehicles into the upper lane.",
                "incident_title": "Flooded underpass near Area 1 approach",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "FCT Abuja",
                "location": "Area 1 Underpass, Abuja",
                "lat": dec("9.026800"),
                "lng": dec("7.488100"),
                "route": "Area 1 - Central District",
                "summary": "Water accumulation is reducing clearance beneath the underpass and redirecting traffic.",
                "minutes_ago": 67,
            },
            {
                "signal_title": "Flooded section on Sapele road by Ring Road",
                "signal_description": "Heavy runoff has covered the curb lane and is slowing movement through the Benin core.",
                "incident_title": "Flooded section on Sapele road by Ring Road",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Edo",
                "location": "Sapele Road by Ring Road, Benin City",
                "lat": dec("6.335000"),
                "lng": dec("5.614100"),
                "route": "Sapele Road",
                "summary": "Floodwater is pooling through a busy urban connector and cutting usable road width.",
                "minutes_ago": 19,
            },
            {
                "signal_title": "Pile-up near Auchi express junction",
                "signal_description": "Two commercial buses and a private car collided close to the junction turnoff.",
                "incident_title": "Pile-up near Auchi express junction",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Auchi Express Junction, Edo",
                "lat": dec("7.073200"),
                "lng": dec("6.264000"),
                "route": "Auchi-Abuja Road",
                "summary": "A collision cluster is slowing traffic and increasing secondary crash risk near the junction.",
                "minutes_ago": 37,
            },
            {
                "signal_title": "Smoke plume from warehouse row in Benin industrial layout",
                "signal_description": "A warehouse fire has produced a heavy smoke column visible across adjoining service roads.",
                "incident_title": "Smoke plume from warehouse row in Benin industrial layout",
                "source": "Drone Patrol Delta-4",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Benin Industrial Layout, Edo",
                "lat": dec("6.388500"),
                "lng": dec("5.640000"),
                "route": "Benin Bypass Service Road",
                "summary": "A warehouse-row fire is degrading air quality and constraining industrial traffic access.",
                "minutes_ago": 54,
            },
            {
                "signal_title": "Obstruction from fallen trailer on Benin bypass",
                "signal_description": "A trailer lost balance and is blocking the outer lane on the bypass shoulder.",
                "incident_title": "Obstruction from fallen trailer on Benin bypass",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Benin Bypass, Edo",
                "lat": dec("6.376200"),
                "lng": dec("5.662100"),
                "route": "Benin Bypass",
                "summary": "A trailer obstruction is spilling congestion onto the bypass and reducing maneuvering space.",
                "minutes_ago": 26,
            },
            {
                "signal_title": "Unsafe route advisory on Ugbowo-Lagos road outbound",
                "signal_description": "Erratic overtaking and shoulder use are rising along an overcrowded outbound stretch.",
                "incident_title": "Unsafe route advisory on Ugbowo-Lagos road outbound",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Ugbowo-Lagos Road Outbound, Edo",
                "lat": dec("6.397200"),
                "lng": dec("5.609400"),
                "route": "Benin - Lagos Road",
                "summary": "The outbound route remains unstable as drivers use unsafe shoulders to bypass delays.",
                "minutes_ago": 31,
            },
            {
                "signal_title": "Erosion-led lane closure near Ekpoma approach",
                "signal_description": "Road-edge erosion has cut into one lane and narrowed access approaching Ekpoma.",
                "incident_title": "Erosion-led lane closure near Ekpoma approach",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Edo",
                "location": "Ekpoma Approach, Edo",
                "lat": dec("6.746600"),
                "lng": dec("6.140900"),
                "route": "Benin-Auchi Road",
                "summary": "Edge failure is forcing a narrow alternating flow on a busy intercity approach.",
                "minutes_ago": 92,
            },
            {
                "signal_title": "Fire outbreak near New Benin market cluster",
                "signal_description": "A cluster of stalls caught fire, sending smoke into adjacent feeder streets.",
                "incident_title": "Fire outbreak near New Benin market cluster",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.RESOLVED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Edo",
                "location": "New Benin Market Cluster, Edo",
                "lat": dec("6.347100"),
                "lng": dec("5.627500"),
                "route": "Mission Road - Ring Road",
                "summary": "A contained market fire disrupted local access before suppression teams brought it under control.",
                "minutes_ago": 148,
            },
            {
                "signal_title": "Road obstruction on East-West Road near Rumuodara",
                "signal_description": "A disabled truck and informal diversion are obstructing a major segment near Rumuodara.",
                "incident_title": "Road obstruction on East-West Road near Rumuodara",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Rivers",
                "location": "East-West Road near Rumuodara, Rivers",
                "lat": dec("4.846600"),
                "lng": dec("6.974000"),
                "route": "East-West Road",
                "summary": "A disabled heavy vehicle is choking one of Port Harcourt's key arterial routes.",
                "minutes_ago": 18,
            },
            {
                "signal_title": "Fire outbreak near Mile 3 market corridor",
                "signal_description": "A roadside fire is spreading smoke through the market corridor and slowing nearby traffic.",
                "incident_title": "Fire outbreak near Mile 3 market corridor",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Rivers",
                "location": "Mile 3 Market Corridor, Rivers",
                "lat": dec("4.790700"),
                "lng": dec("6.997300"),
                "route": "Ikwerre Road",
                "summary": "A market-corridor fire is forcing local rerouting and reducing air visibility.",
                "minutes_ago": 44,
            },
            {
                "signal_title": "Unsafe route advisory on Eleme refinery approach",
                "signal_description": "Stop-start heavy truck movement is driving risky overtaking on the refinery approach.",
                "incident_title": "Unsafe route advisory on Eleme refinery approach",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Rivers",
                "location": "Eleme Refinery Approach, Rivers",
                "lat": dec("4.789400"),
                "lng": dec("7.123500"),
                "route": "Alesa-Eleme Road",
                "summary": "The refinery approach remains unstable as trucks compress lanes and trigger risky passing behavior.",
                "minutes_ago": 61,
            },
            {
                "signal_title": "Tanker breakdown blocking Mowe outbound lane",
                "signal_description": "A broken-down tanker is blocking the outbound lane and pushing traffic onto the shoulder.",
                "incident_title": "Tanker breakdown blocking Mowe outbound lane",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Ogun",
                "location": "Mowe Outbound Lane, Ogun",
                "lat": dec("6.814000"),
                "lng": dec("3.915100"),
                "route": "Lagos-Ibadan Expressway",
                "summary": "A tanker breakdown is narrowing throughput at one of the busiest gateway stretches into Ogun.",
                "minutes_ago": 21,
            },
            {
                "signal_title": "Flooded stretch near Abeokuta-Sagamu interchange",
                "signal_description": "Runoff has covered a low segment approaching the interchange and is slowing traffic rotation.",
                "incident_title": "Flooded stretch near Abeokuta-Sagamu interchange",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Ogun",
                "location": "Abeokuta-Sagamu Interchange, Ogun",
                "lat": dec("7.128500"),
                "lng": dec("3.412000"),
                "route": "Sagamu-Abeokuta Road",
                "summary": "A flooded low point is slowing the interchange approach and forcing shallow detours.",
                "minutes_ago": 88,
            },
            {
                "signal_title": "Multi-vehicle crash near Iwo Road interchange",
                "signal_description": "Two buses and a sedan collided close to the interchange ramp during heavy merging.",
                "incident_title": "Multi-vehicle crash near Iwo Road interchange",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Oyo",
                "location": "Iwo Road Interchange, Oyo",
                "lat": dec("7.412100"),
                "lng": dec("3.947200"),
                "route": "Iwo Road Corridor",
                "summary": "A fresh interchange crash is causing abrupt lane shifts and intermittent full stops.",
                "minutes_ago": 25,
            },
            {
                "signal_title": "Fire outbreak near Bodija market service lane",
                "signal_description": "A service-lane fire is affecting nearby stalls and creating smoke cover over the feeder road.",
                "incident_title": "Fire outbreak near Bodija market service lane",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Oyo",
                "location": "Bodija Market Service Lane, Oyo",
                "lat": dec("7.438100"),
                "lng": dec("3.895800"),
                "route": "Bodija - Secretariat Road",
                "summary": "A small market-lane fire is affecting local movement and roadside business access.",
                "minutes_ago": 79,
            },
            {
                "signal_title": "Flooded segment near DSC roundabout axis",
                "signal_description": "Surface water has collected through the roundabout axis and is slowing heavy vehicles.",
                "incident_title": "Flooded segment near DSC roundabout axis",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Delta",
                "location": "DSC Roundabout Axis, Delta",
                "lat": dec("5.565200"),
                "lng": dec("5.793000"),
                "route": "Effurun-Warri Road",
                "summary": "Floodwater is slowing the roundabout axis and reducing visibility for merging traffic.",
                "minutes_ago": 29,
            },
            {
                "signal_title": "Unsafe route advisory on Asaba-Onitsha connector",
                "signal_description": "Erratic lane changes and shoulder driving are increasing risk on the bridge connector.",
                "incident_title": "Unsafe route advisory on Asaba-Onitsha connector",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Delta",
                "location": "Asaba-Onitsha Connector, Delta",
                "lat": dec("6.198700"),
                "lng": dec("6.737800"),
                "route": "Niger Bridge Connector",
                "summary": "The bridge connector remains risky as compression triggers aggressive maneuvering near merge points.",
                "minutes_ago": 52,
            },
            {
                "signal_title": "Obstruction from stalled truck near Ninth Mile descent",
                "signal_description": "A stalled truck is blocking part of the descent and backing traffic into the climb lane.",
                "incident_title": "Obstruction from stalled truck near Ninth Mile descent",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Enugu",
                "location": "Ninth Mile Descent, Enugu",
                "lat": dec("6.518700"),
                "lng": dec("7.396800"),
                "route": "Enugu-Onitsha Expressway",
                "summary": "A stalled truck is constricting the descent and creating a queue with limited escape space.",
                "minutes_ago": 33,
            },
            {
                "signal_title": "Fire outbreak near Sabon Gari logistics row",
                "signal_description": "A logistics-row fire is producing smoke and constraining access through the distribution area.",
                "incident_title": "Fire outbreak near Sabon Gari logistics row",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Kano",
                "location": "Sabon Gari Logistics Row, Kano",
                "lat": dec("12.002200"),
                "lng": dec("8.516900"),
                "route": "Sabon Gari - IBB Way",
                "summary": "A contained fire is degrading visibility and interrupting access through a busy logistics strip.",
                "minutes_ago": 73,
            },
            {
                "signal_title": "Flood surge near Marina slipway access",
                "signal_description": "Backflow water is covering the slipway access and slowing vehicles entering the marina edge.",
                "incident_title": "Flood surge near Marina slipway access",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Marina Slipway Access, Lagos",
                "lat": dec("6.451200"),
                "lng": dec("3.397300"),
                "route": "Marina - CMS",
                "summary": "A flood surge is cutting access to the marina edge and causing lane compression near the waterfront.",
                "minutes_ago": 15,
            },
            {
                "signal_title": "Crash cluster near Epe express merge segment",
                "signal_description": "A fresh crash cluster has formed along the merge segment with debris forcing abrupt lane changes.",
                "incident_title": "Crash cluster near Epe express merge segment",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Epe Express Merge Segment, Lagos",
                "lat": dec("6.603800"),
                "lng": dec("3.975500"),
                "route": "Lekki-Epe Expressway",
                "summary": "Multiple impacted vehicles are slowing the merge segment and creating a high-risk bottleneck.",
                "minutes_ago": 39,
            },
            {
                "signal_title": "Unsafe route buildup around Dopemu interchange",
                "signal_description": "Commercial buses are forcing tight merges and shoulder use around the interchange during peak movement.",
                "incident_title": "Unsafe route buildup around Dopemu interchange",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Lagos",
                "location": "Dopemu Interchange, Lagos",
                "lat": dec("6.638000"),
                "lng": dec("3.333800"),
                "route": "Agege Motor Road",
                "summary": "An unstable merge pattern is pushing risky maneuvers through the interchange approaches.",
                "minutes_ago": 49,
            },
            {
                "signal_title": "Road obstruction from stalled bus at Falomo ramp",
                "signal_description": "A stalled high-capacity bus is blocking one ramp lane and spilling traffic back toward the bridge.",
                "incident_title": "Road obstruction from stalled bus at Falomo ramp",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Falomo Ramp, Lagos",
                "lat": dec("6.439900"),
                "lng": dec("3.434200"),
                "route": "Ikoyi Bridge Ramp",
                "summary": "A stalled bus is constraining the ramp and causing queueing back toward the bridge crossing.",
                "minutes_ago": 97,
            },
            {
                "signal_title": "Smoke flare near Alaka service corridor",
                "signal_description": "A roadside flare-up is pushing smoke into the service corridor and reducing short-range visibility.",
                "incident_title": "Smoke flare near Alaka service corridor",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Lagos",
                "location": "Alaka Service Corridor, Lagos",
                "lat": dec("6.480500"),
                "lng": dec("3.365300"),
                "route": "Western Avenue Connector",
                "summary": "A localized flare-up is disrupting service-lane movement and slowing access into the connector corridor.",
                "minutes_ago": 108,
            },
            {
                "signal_title": "Flood pressure at Ramat Park feeder lane",
                "signal_description": "Runoff is collecting through the feeder lane and pushing minibuses into tighter merge space.",
                "incident_title": "Flood pressure at Ramat Park feeder lane",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Edo",
                "location": "Ramat Park Feeder Lane, Edo",
                "lat": dec("6.359800"),
                "lng": dec("5.603400"),
                "route": "Ramat Park Corridor",
                "summary": "Flood pressure is reducing the feeder lane width and increasing conflict at the merge point.",
                "minutes_ago": 17,
            },
            {
                "signal_title": "Collision near Uselu rail crossing",
                "signal_description": "A two-vehicle collision near the crossing is slowing flow and attracting roadside spillover.",
                "incident_title": "Collision near Uselu rail crossing",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Uselu Rail Crossing, Edo",
                "lat": dec("6.366900"),
                "lng": dec("5.622600"),
                "route": "Uselu-Lagos Road",
                "summary": "A crossing-side collision is constraining movement and raising secondary incident risk.",
                "minutes_ago": 28,
            },
            {
                "signal_title": "Unsafe route advisory near Aduwawa axis",
                "signal_description": "Buses and trucks are forcing aggressive merges through a compressed urban segment.",
                "incident_title": "Unsafe route advisory near Aduwawa axis",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Aduwawa Axis, Edo",
                "lat": dec("6.400100"),
                "lng": dec("5.668000"),
                "route": "Benin-Auchi Road",
                "summary": "Dense vehicle interaction is turning the Aduwawa axis into an unstable corridor for through traffic.",
                "minutes_ago": 42,
            },
            {
                "signal_title": "Road obstruction near Upper Mission junction",
                "signal_description": "A disabled truck is blocking one turn lane near the junction and slowing market-bound traffic.",
                "incident_title": "Road obstruction near Upper Mission junction",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Edo",
                "location": "Upper Mission Junction, Edo",
                "lat": dec("6.315800"),
                "lng": dec("5.601200"),
                "route": "Upper Mission Road",
                "summary": "A blocked turn lane is reducing throughput and spilling delay into the junction approaches.",
                "minutes_ago": 86,
            },
            {
                "signal_title": "Warehouse-side flare near Sapele bypass spur",
                "signal_description": "A warehouse-side flare has produced smoke cover across the bypass spur and slowed industrial traffic.",
                "incident_title": "Warehouse-side flare near Sapele bypass spur",
                "source": "Drone Patrol Delta-4",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FIRE_OUTBREAK,
                "incident_type": IncidentType.FIRE_OUTBREAK,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Edo",
                "location": "Sapele Bypass Spur, Edo",
                "lat": dec("6.381600"),
                "lng": dec("5.588900"),
                "route": "Sapele Bypass Spur",
                "summary": "Smoke from a flare-up is degrading visibility and slowing warehouse access traffic.",
                "minutes_ago": 63,
            },
            {
                "signal_title": "Crash at Kubwa toll approach lane",
                "signal_description": "A fresh impact near the toll approach is forcing lane weaving and slowing inbound traffic.",
                "incident_title": "Crash at Kubwa toll approach lane",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "FCT Abuja",
                "location": "Kubwa Toll Approach Lane, Abuja",
                "lat": dec("9.154400"),
                "lng": dec("7.323600"),
                "route": "Kubwa Express Corridor",
                "summary": "A toll-approach crash is disrupting inbound flow and producing unstable lane shifts.",
                "minutes_ago": 19,
            },
            {
                "signal_title": "Unsafe route pressure around Nyanya inbound",
                "signal_description": "Commercial traffic is compressing the inbound lane and triggering shoulder use near Nyanya.",
                "incident_title": "Unsafe route pressure around Nyanya inbound",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "FCT Abuja",
                "location": "Nyanya Inbound Corridor, Abuja",
                "lat": dec("8.994800"),
                "lng": dec("7.603200"),
                "route": "Nyanya - Central Abuja",
                "summary": "The inbound corridor remains unstable as pressure builds along a constrained commuter segment.",
                "minutes_ago": 44,
            },
            {
                "signal_title": "Road obstruction near Port Harcourt Aba connector",
                "signal_description": "A heavy truck has broken down near the connector and is reducing usable carriageway width.",
                "incident_title": "Road obstruction near Port Harcourt Aba connector",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Rivers",
                "location": "Port Harcourt Aba Connector, Rivers",
                "lat": dec("4.820100"),
                "lng": dec("7.017000"),
                "route": "Aba Road Connector",
                "summary": "A heavy breakdown is slowing the connector and forcing tight merges around the obstruction.",
                "minutes_ago": 24,
            },
            {
                "signal_title": "Flooded section near Waterlines roundabout",
                "signal_description": "Surface water has spread through the roundabout exits and is slowing mixed traffic movement.",
                "incident_title": "Flooded section near Waterlines roundabout",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Rivers",
                "location": "Waterlines Roundabout, Rivers",
                "lat": dec("4.815900"),
                "lng": dec("7.005300"),
                "route": "Waterlines - GRA",
                "summary": "Flooding around the exits is slowing circulation and increasing conflict between turning vehicles.",
                "minutes_ago": 77,
            },
            {
                "signal_title": "Unsafe route buildup near Sagamu split",
                "signal_description": "Queue spillback and trailer overtakes are increasing instability near the highway split.",
                "incident_title": "Unsafe route buildup near Sagamu split",
                "source": "Northwest Civic Monitor",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.UNSAFE_ROUTE,
                "incident_type": IncidentType.UNSAFE_ROUTE,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.HIGH,
                "state": "Ogun",
                "location": "Sagamu Split, Ogun",
                "lat": dec("6.841500"),
                "lng": dec("3.650600"),
                "route": "Sagamu Interchange",
                "summary": "Heavy queue spillback is triggering aggressive overtakes near the split and reducing safe separation.",
                "minutes_ago": 36,
            },
            {
                "signal_title": "Crash near Challenge roundabout outbound",
                "signal_description": "A two-vehicle impact near the roundabout is slowing outbound flow and backing traffic into the feeder lane.",
                "incident_title": "Crash near Challenge roundabout outbound",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.HIGH,
                "state": "Oyo",
                "location": "Challenge Roundabout Outbound, Oyo",
                "lat": dec("7.355100"),
                "lng": dec("3.859900"),
                "route": "Challenge - Ring Road",
                "summary": "An outbound crash is reducing roundabout circulation and increasing approach delays.",
                "minutes_ago": 31,
            },
            {
                "signal_title": "Flooded lane near Asaba cable point",
                "signal_description": "Runoff has overtaken the left lane and is forcing uneven merges near the cable point.",
                "incident_title": "Flooded lane near Asaba cable point",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.HIGH,
                "severity": SeverityLevel.MEDIUM,
                "state": "Delta",
                "location": "Asaba Cable Point, Delta",
                "lat": dec("6.211700"),
                "lng": dec("6.729500"),
                "route": "Asaba Urban Connector",
                "summary": "A flooded lane is creating uneven merges and slowing urban connector traffic through Asaba.",
                "minutes_ago": 26,
            },
            {
                "signal_title": "Road obstruction near Ogbete market approach",
                "signal_description": "A delivery truck is partially blocking the approach and disrupting turning traffic into the market edge.",
                "incident_title": "Road obstruction near Ogbete market approach",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_OBSTRUCTION,
                "incident_type": IncidentType.ROAD_OBSTRUCTION,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Enugu",
                "location": "Ogbete Market Approach, Enugu",
                "lat": dec("6.448900"),
                "lng": dec("7.504700"),
                "route": "Ogbete - Okpara Avenue",
                "summary": "A partial blockage is constraining market-edge movement and forcing tight turns in a dense approach lane.",
                "minutes_ago": 81,
            },
            {
                "signal_title": "Flooded crossing near Kawo junction",
                "signal_description": "Water pooling near the junction is slowing the crossing and increasing braking pressure.",
                "incident_title": "Flooded crossing near Kawo junction",
                "source": "Rapid Response Hotline",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.FLOODING,
                "incident_type": IncidentType.FLOODING,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.ACTIVE,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Kaduna",
                "location": "Kawo Junction Crossing, Kaduna",
                "lat": dec("10.553400"),
                "lng": dec("7.438900"),
                "route": "Kawo - Independence Way",
                "summary": "A flooded crossing is reducing speed and raising lane-change conflict near a busy junction.",
                "minutes_ago": 57,
            },
            {
                "signal_title": "Crash near Dangi bridge descent",
                "signal_description": "A minor crash on the descent is slowing lane recovery and tightening spacing over the bridge approach.",
                "incident_title": "Crash near Dangi bridge descent",
                "source": "Transport Union Watch",
                "cluster": None,
                "pattern": None,
                "category": SignalCategory.ROAD_ACCIDENT,
                "incident_type": IncidentType.ROAD_ACCIDENT,
                "signal_status": SignalStatus.TRIAGED,
                "incident_status": IncidentStatus.VERIFIED,
                "confidence": ConfidenceLevel.CORROBORATED,
                "severity": SeverityLevel.MEDIUM,
                "state": "Kano",
                "location": "Dangi Bridge Descent, Kano",
                "lat": dec("11.994500"),
                "lng": dec("8.530400"),
                "route": "Dangi Bridge Connector",
                "summary": "A descent-side collision is slowing traffic recovery and producing tighter spacing over the bridge segment.",
                "minutes_ago": 69,
            },
        ]

    def _ensure_signals(self, user, sources, clusters, now):
        signals = []
        for spec in self._demo_incident_specs():
            signal, _ = Signal.objects.update_or_create(
                title=spec["signal_title"],
                defaults={
                    "description": spec["signal_description"],
                    "source_profile": sources[spec["source"]],
                    "submitted_by": user,
                    "cluster": clusters.get(spec["cluster"]) if spec["cluster"] else None,
                    "category": spec["category"],
                    "status": spec["signal_status"],
                    "confidence": spec["confidence"],
                    "severity": spec["severity"],
                    "location_name": spec["location"],
                    "latitude": spec["lat"],
                    "longitude": spec["lng"],
                    "coordinate_precision_meters": 90,
                    "route_hint": spec["route"],
                    "occurred_at": now - timedelta(minutes=spec["minutes_ago"]),
                    "extracted_entities": [spec["location"], spec["route"]],
                    "metadata": {
                        **DEMO_FLAG,
                        "location_state": spec["state"],
                    },
                },
            )
            Signal.objects.filter(pk=signal.pk).update(
                received_at=now - timedelta(minutes=max(1, spec["minutes_ago"] - 2)),
                created_at=now - timedelta(minutes=max(1, spec["minutes_ago"] - 2)),
                updated_at=now - timedelta(minutes=max(1, spec["minutes_ago"] - 1)),
            )
            signals.append(signal)
        return signals

    def _ensure_incidents(self, patterns, signals, now):
        signals_by_title = {signal.title: signal for signal in signals}
        incidents = []
        for spec in self._demo_incident_specs():
            incident, _ = Incident.objects.update_or_create(
                title=spec["incident_title"],
                defaults={
                    "incident_type": spec["incident_type"],
                    "pattern": patterns.get(spec["pattern"]) if spec["pattern"] else None,
                    "primary_signal": signals_by_title[spec["signal_title"]],
                    "confidence": spec["confidence"],
                    "severity": spec["severity"],
                    "status": spec["incident_status"],
                    "location_name": spec["location"],
                    "latitude": spec["lat"],
                    "longitude": spec["lng"],
                    "started_at": now - timedelta(minutes=spec["minutes_ago"] + 12),
                    "summary": spec["summary"],
                    "metadata": {
                        **DEMO_FLAG,
                        "location_state": spec["state"],
                        "last_reconfirmed_at": (now - timedelta(minutes=max(1, spec["minutes_ago"] - 3))).isoformat(),
                        "decay_started_at": (now - timedelta(minutes=spec["minutes_ago"] + 12)).isoformat(),
                    },
                },
            )
            Incident.objects.filter(pk=incident.pk).update(
                detected_at=now - timedelta(minutes=spec["minutes_ago"]),
                created_at=now - timedelta(minutes=spec["minutes_ago"]),
                updated_at=now - timedelta(minutes=max(1, spec["minutes_ago"] - 2)),
            )
            incidents.append(incident)
        return incidents

    def _ensure_risk_snapshots(self, watch_zones, patterns, incidents, now):
        incident_by_title = {incident.title: incident for incident in incidents}
        snapshots = [
            {
                "zone": watch_zones["Lekki Peninsula"],
                "pattern": patterns["Lekki commuter threat escalation"],
                "incident": incident_by_title["Armed robbery cluster near Lekki toll corridor"],
                "risk_level": RiskLevel.HIGH,
                "risk_score": Decimal("78.50"),
                "rationale": "Robbery cluster and movement pattern align with peak commuter vulnerability.",
            },
            {
                "zone": watch_zones["Abuja Southern Approach"],
                "pattern": None,
                "incident": incident_by_title["Abuja southbound anomaly watch"],
                "risk_level": RiskLevel.MEDIUM,
                "risk_score": Decimal("64.20"),
                "rationale": "Anomaly reports remain unconfirmed but persistent.",
            },
            {
                "zone": watch_zones["Kaduna Forest Edge"],
                "pattern": patterns["Kaduna staging pattern"],
                "incident": incident_by_title["Kaduna forest edge staging activity"],
                "risk_level": RiskLevel.CRITICAL,
                "risk_score": Decimal("91.40"),
                "rationale": "High confidence staging pattern with fresh corroborating indicators.",
            },
        ]

        for snapshot in snapshots:
            RiskSnapshot.objects.update_or_create(
                watch_zone=snapshot["zone"],
                incident=snapshot["incident"],
                defaults={
                    "pattern": snapshot["pattern"],
                    "risk_level": snapshot["risk_level"],
                    "risk_score": snapshot["risk_score"],
                    "rationale": snapshot["rationale"],
                    "factors": DEMO_FLAG,
                },
            )

    def _ensure_alerts(self, rules, watch_zones, geofences, clusters, patterns, incidents, now):
        incident_by_title = {incident.title: incident for incident in incidents}
        specs = [
            {
                "title": "Critical robbery escalation on Lekki corridor",
                "message": "Fresh critical incident detected near the commuter corridor. Analysts should verify route disruption and deploy response guidance.",
                "severity": SeverityLevel.CRITICAL,
                "watch_zone": watch_zones["Lekki Peninsula"],
                "geofence": geofences["Lekki-Epe Expressway Corridor"],
                "cluster": clusters["Lekki night movement cluster"],
                "pattern": patterns["Lekki commuter threat escalation"],
                "incident": incident_by_title["Armed robbery cluster near Lekki toll corridor"],
                "rule": rules["High severity corroborated incident"],
                "minutes_ago": 8,
            },
            {
                "title": "Forest edge staging alert",
                "message": "High confidence staging activity remains active near Kaduna forest ingress. Monitor route closures and nearby settlements.",
                "severity": SeverityLevel.CRITICAL,
                "watch_zone": watch_zones["Kaduna Forest Edge"],
                "geofence": None,
                "cluster": clusters["Kaduna forest ingress cluster"],
                "pattern": patterns["Kaduna staging pattern"],
                "incident": incident_by_title["Kaduna forest edge staging activity"],
                "rule": rules["High severity corroborated incident"],
                "minutes_ago": 13,
            },
            {
                "title": "Abuja southbound anomaly watch",
                "message": "Emerging anomaly reports continue near the southern approach. Maintain analyst monitoring and collect corroboration.",
                "severity": SeverityLevel.MEDIUM,
                "watch_zone": watch_zones["Abuja Southern Approach"],
                "geofence": geofences["Abuja City Gate Perimeter"],
                "cluster": None,
                "pattern": None,
                "incident": incident_by_title["Abuja southbound anomaly watch"],
                "rule": rules["Escalating corridor activity"],
                "minutes_ago": 36,
            },
        ]

        alerts = []
        for spec in specs:
            alert, _ = Alert.objects.update_or_create(
                title=spec["title"],
                defaults={
                    "rule": spec["rule"],
                    "watch_zone": spec["watch_zone"],
                    "geofence": spec["geofence"],
                    "cluster": spec["cluster"],
                    "pattern": spec["pattern"],
                    "incident": spec["incident"],
                    "severity": spec["severity"],
                    "status": "open",
                    "message": spec["message"],
                    "metadata": DEMO_FLAG,
                },
            )
            Alert.objects.filter(pk=alert.pk).update(
                triggered_at=now - timedelta(minutes=spec["minutes_ago"]),
            )
            alerts.append(alert)
        return alerts
