# Generated by Django 5.2.5 on 2026-05-21 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('user', 'User'), ('anonymous', 'Anonymous'), ('ngo', 'NGO'), ('journalist', 'Journalist'), ('transport', 'Transport Network'), ('civic_monitor', 'Civic Monitor'), ('patrol', 'Patrol'), ('drone', 'Drone'), ('social', 'Social Feed'), ('public_data', 'Public Dataset')], default='user', max_length=32)),
                ('reliability_band', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('trusted', 'Trusted')], default='moderate', max_length=16)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('verified_signal_count', models.PositiveIntegerField(default=0)),
                ('disputed_signal_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('community_reporter', 'Community Reporter'), ('trusted_verifier', 'Trusted Verifier'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='community_reporter', max_length=32)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('region_name', models.CharField(blank=True, max_length=255)),
                ('is_active_operator', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
