# Generated by Django 5.2.5 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geofence_type', models.CharField(choices=[('school', 'School'), ('village', 'Village'), ('highway', 'Highway'), ('pipeline', 'Pipeline'), ('facility', 'Facility'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('boundary', models.JSONField(blank=True, default=dict)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notify_on_signal', models.BooleanField(default=True)),
                ('notify_on_incident', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
