# Generated by Django 5.2.5 on 2026-05-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(default='custom', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('current_risk_level', models.CharField(choices=[('baseline', 'Baseline'), ('elevated_watch', 'Elevated Watch'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk'), ('critical_alert', 'Critical Alert')], default='baseline', max_length=16)),
                ('current_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('baseline', 'Baseline'), ('elevated_watch', 'Elevated Watch'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk'), ('critical_alert', 'Critical Alert')], default='baseline', max_length=16)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rationale', models.TextField(blank=True)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_snapshots', to='incidents.incident')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_snapshots', to='incidents.pattern')),
                ('watch_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='risk.watchzone')),
            ],
            options={
                'ordering': ['-snapshot_at'],
            },
        ),
    ]
