# Generated by Django 5.2.5 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('threat_activity', 'Threat Activity'), ('violence', 'Violence'), ('kidnapping', 'Kidnapping'), ('armed_robbery', 'Armed Robbery'), ('road_blockade', 'Road Blockade'), ('fire', 'Fire'), ('flood', 'Flood'), ('other', 'Other')], default='threat_activity', max_length=32)),
                ('confidence', models.CharField(choices=[('raw', 'Raw'), ('low', 'Low Confidence'), ('emerging', 'Emerging'), ('corroborated', 'Corroborated'), ('high', 'High Confidence'), ('disputed', 'Disputed')], default='corroborated', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('confidence', models.CharField(choices=[('raw', 'Raw'), ('low', 'Low Confidence'), ('emerging', 'Emerging'), ('corroborated', 'Corroborated'), ('high', 'High Confidence'), ('disputed', 'Disputed')], default='emerging', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('emerging', 'Emerging'), ('monitoring', 'Monitoring'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='emerging', max_length=16)),
                ('geographic_hint', models.CharField(blank=True, max_length=255)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('first_detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cluster_type', models.CharField(choices=[('proximity', 'Spatial Proximity'), ('route', 'Route Pattern'), ('movement', 'Movement Pattern'), ('environmental', 'Environmental Pattern'), ('mixed', 'Mixed')], default='proximity', max_length=16)),
                ('confidence', models.CharField(choices=[('raw', 'Raw'), ('low', 'Low Confidence'), ('emerging', 'Emerging'), ('corroborated', 'Corroborated'), ('high', 'High Confidence'), ('disputed', 'Disputed')], default='low', max_length=16)),
                ('status', models.CharField(choices=[('emerging', 'Emerging'), ('monitoring', 'Monitoring'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='emerging', max_length=16)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
