# Generated by Django 5.2.5 on 2026-05-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='primary_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_incidents', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='incident',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.pattern'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns', to='incidents.signalcluster'),
        ),
    ]
